### PR TITLE
Script to create vtks from Freesurfer surface and annot files.

### PR DESCRIPTION
**Pull request by bcipolli**
This depends on #3. Title says it all.

This introduces dependencies on:
- `numpy`
- `mindboggle`

Live demo (with two hemispheres using the Destrieux parcellation) here:
http://cseweb.ucsd.edu/~bcipolli/roygbiv/
Note that this demo breaks the box plots... but that the box plots do work when using the original data. All the code works, just don't have the box plot data for the Destrieux parcellation.

screen shot 2015-10-02 at 9 20 37 pm
screen shot 2015-10-02 at 9 20 43 pm

### CODE REVIEW

**Comment by bcipolli** [comment]
Just separated this more cleanly into two demos:
http://cseweb.ucsd.edu/~bcipolli/roygbiv/index.html (original demo)
http://cseweb.ucsd.edu/~bcipolli/roygbiv/two_hemis.html (left and right hemis)

**Comment by bcipolli** [comment]
I broke something about this demo between yesterday and today. Debugging...

**Comment by bcipolli** [comment]
Fixed. Should be ready to go.
image

**Comment by binarybottle** [comment]
It sure would be nice to have the option to have both hemispheres side by side with a graph that responds to interaction with either hemisphere (or two plots).  Is it easy to resize the windows (vignettes) to scale up the brain?

**Comment by bcipolli** [comment]
Yes. The brain uses the div size to scale itself. So, just change the CSS properties of the container that's passed to the brain. You can also position the divs via CSS. To change camera views, you'll have to mess with the `brain.camera`.

**Pull request merged**
